-- Manual SQL script to add recurrence fields to Events table
-- Execute this in Oracle SQL*Plus if migrations fail

BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EVENTS ADD ISRECURRENCEPARENT NUMBER(1) DEFAULT 0';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-1430, -955) THEN RAISE; END IF;
  END;

  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EVENTS ADD PARENTEVENTID NUMBER(10)';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-1430, -955) THEN RAISE; END IF;
  END;

  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EVENTS ADD RECURRENCEDAYSOFWEEK VARCHAR2(100)';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-1430, -955) THEN RAISE; END IF;
  END;

  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EVENTS ADD RECURRENCEENDCOUNT NUMBER(10)';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-1430, -955) THEN RAISE; END IF;
  END;

  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EVENTS ADD RECURRENCEENDDATE TIMESTAMP(7)';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-1430, -955) THEN RAISE; END IF;
  END;

  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EVENTS ADD RECURRENCETYPE VARCHAR2(50)';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-1430, -955) THEN RAISE; END IF;
  END;
END;
/
