apiVersion: v1
kind: Service
metadata:
  name: project-manager-backend
  labels:
    app: project-manager-backend
    component: api
spec:
  type: ClusterIP
  selector:
    app: project-manager-backend
  ports:
  - name: http
    port: 5000
    targetPort: http
    protocol: TCP
  sessionAffinity: None
