// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProjectManagerWebAPI.Data;

#nullable disable

namespace ProjectManagerWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260702185213_AddSeurGuiasModule")]
    partial class AddSeurGuiasModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectManagerWebAPI.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("FreshDeskId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Manager")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Priority")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("SetorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SetorId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.ProjectManagerHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FromManager")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ToManager")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectManagerHistories");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.ProjectMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.ProjectOwnerHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FromOwner")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ToOwner")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectOwnerHistories");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.ProjectStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Reason")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectStatusHistories");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.ProjectTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualHours")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("EstimatedHours")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal?>("Progress")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.SeurErro", b =>
                {
                    b.Property<long>("Idt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("IDT");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Idt"));

                    b.Property<DateTime?>("DatahoraInsert")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATAHORA_INSERT");

                    b.Property<string>("Detail")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DETAIL");

                    b.Property<string>("Ecb")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ECB");

                    b.Property<string>("Referencia")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REFERENCIA");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TITLE");

                    b.HasKey("Idt");

                    b.ToTable("SEUR_ERRO", "SEUR", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.SeurGuia", b =>
                {
                    b.Property<long>("Idt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("IDT");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Idt"));

                    b.Property<string>("Apagado")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("APAGADO");

                    b.Property<string>("Cccc")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CCCC");

                    b.Property<string>("CodCentro")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("COD_CENTRO");

                    b.Property<string>("CodeStatusAtlas")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODESTATUSATLAS");

                    b.Property<string>("ContaDpd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CONTADPD");

                    b.Property<DateTime?>("DataVerifyTrace")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATAVERIFYTRACE");

                    b.Property<string>("Destino")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINO");

                    b.Property<string>("DestinoCodigoPostal")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINOCODIGOPOSTAL");

                    b.Property<string>("DestinoContatoEmail")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINOCONTATOEMAIL");

                    b.Property<string>("DestinoContatoNome")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINOCONTATONOME");

                    b.Property<string>("DestinoContatoTelefone")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINOCONTATOTELEFONE");

                    b.Property<string>("DestinoContatoTelemovel")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINOCONTATOTELEMOVEL");

                    b.Property<string>("DestinoEmail")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINOEMAIL");

                    b.Property<string>("DestinoFax")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINOFAX");

                    b.Property<string>("DestinoLocalidade")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINOLOCALIDADE");

                    b.Property<string>("DestinoMorada")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINOMORADA");

                    b.Property<string>("DestinoMoradaComplemento")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINOMORADACOMPLEMENTO");

                    b.Property<string>("DestinoNome")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINONOME");

                    b.Property<string>("DestinoPais")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINOPAIS");

                    b.Property<string>("DestinoPraca")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINOPRACA");

                    b.Property<string>("DestinoTelefone")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINOTELEFONE");

                    b.Property<string>("DestinoTelemovel")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESTINOTELEMOVEL");

                    b.Property<string>("Digito")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DIGITO");

                    b.Property<DateTime>("DtAlteracao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ALTERACAO");

                    b.Property<DateTime?>("DtAtlas")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATLAS");

                    b.Property<DateTime?>("DtCit")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CIT");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("FlagAs400")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FLAG_AS400");

                    b.Property<string>("FlagAtlas")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FLAGATLAS");

                    b.Property<string>("FlagCit")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FLAGCIT");

                    b.Property<string>("Guia")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("GUIA");

                    b.Property<string>("GuiaDpd")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("GUIADPD");

                    b.Property<long?>("IdRange")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("IDRANGE");

                    b.Property<string>("Obs")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OBS");

                    b.Property<string>("ObsAdd")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OBSADD");

                    b.Property<string>("OrigemCodigoPostal")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEMCODIGOPOSTAL");

                    b.Property<string>("OrigemContatoEmail")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEMCONTATOEMAIL");

                    b.Property<string>("OrigemContatoNome")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEMCONTATONOME");

                    b.Property<string>("OrigemContatoTelefone")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEMCONTATOTELEFONE");

                    b.Property<string>("OrigemContatoTelemovel")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEMCONTATOTELEMOVEL");

                    b.Property<string>("OrigemEmail")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEMEMAIL");

                    b.Property<string>("OrigemFax")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEMFAX");

                    b.Property<string>("OrigemLocalidade")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEMLOCALIDADE");

                    b.Property<string>("OrigemMorada")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEMMORADA");

                    b.Property<string>("OrigemMoradaComplemento")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEMMORADACOMPLEMENTO");

                    b.Property<string>("OrigemNome")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEMNOME");

                    b.Property<string>("OrigemPais")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEMPAIS");

                    b.Property<string>("OrigemPraca")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEMPRACA");

                    b.Property<string>("OrigemTelefone")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEMTELEFONE");

                    b.Property<string>("OrigemTelemovel")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORIGEMTELEMOVEL");

                    b.Property<string>("ParcelNumber")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PARCELNUMBER");

                    b.Property<long?>("Peso")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PESO");

                    b.Property<string>("Product")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PRODUCT");

                    b.Property<string>("ProdutoCodigo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PRODUTOCODIGO");

                    b.Property<long?>("QtdVolumes")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("QTDVOLUMES");

                    b.Property<string>("Range")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RANGE");

                    b.Property<string>("Referencia")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REFERENCIA");

                    b.Property<string>("RequestAtlas")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REQUESTATLAS");

                    b.Property<string>("RespAtlas")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RESP_ATLAS");

                    b.Property<string>("RespCit")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RESPCIT");

                    b.Property<string>("Service")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SERVICE");

                    b.Property<string>("ServicoCodigo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SERVICOCODIGO");

                    b.Property<string>("ShipmentCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SHIPMENTCODE");

                    b.Property<string>("TransportLine")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TRANSPORTLINE");

                    b.Property<long?>("UserId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USERID");

                    b.Property<long?>("ValorCod")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("VALORCOD");

                    b.Property<string>("VerifyDatahoraInc")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("VERIFY_DATAHORA_INC");

                    b.Property<DateTime?>("VerifyDatahoraUpd")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("VERIFY_DATAHORA_UPD");

                    b.Property<string>("VerifyFlag")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("VERIFY_FLAG");

                    b.Property<string>("VerifyInc")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("VERIFY_INC");

                    b.Property<string>("VerifyResp")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("VERIFY_RESP");

                    b.Property<string>("VerifyTrace")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("VERIFYTRACE");

                    b.HasKey("Idt");

                    b.ToTable("SEUR_GUIA", "SEUR", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.SeurParcel", b =>
                {
                    b.Property<long>("Idt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("IDT");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Idt"));

                    b.Property<DateTime?>("DatahoraInsert")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATAHORA_INSERT");

                    b.Property<string>("Ecbs")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ECBS");

                    b.Property<string>("Flag")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FLAG");

                    b.Property<string>("ParcelNumbers")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PARCELNUMBERS");

                    b.Property<string>("ShipmentCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SHIPMENTCODE");

                    b.HasKey("Idt");

                    b.ToTable("SEUR_PARCEL", "CHRONO_WEB", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.SeurUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Role")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("SeurUsers");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.SeurVerify", b =>
                {
                    b.Property<long>("Idt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("IDT");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Idt"));

                    b.Property<string>("Dat")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DAT");

                    b.Property<DateTime?>("DatahoraInsert")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATAHORA_INSERT");

                    b.Property<string>("Guia")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("GUIA");

                    b.Property<string>("Hor")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("HOR");

                    b.Property<string>("Inc")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INC");

                    b.Property<DateTime?>("VerifyData")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("VERIFY_DATA");

                    b.Property<string>("VerifyFlag")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("VERIFY_FLAG");

                    b.Property<string>("VerifyResposta")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("VERIFY_RESPOSTA");

                    b.HasKey("Idt");

                    b.ToTable("VERIFY_SEUR", "CHRONO_WEB", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Department")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Role")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.UserSetor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("SetorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.HasIndex("UserId", "SetorId")
                        .IsUnique();

                    b.ToTable("UserSetores");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.Comment", b =>
                {
                    b.HasOne("ProjectManagerWebAPI.Models.Project", "Project")
                        .WithMany("Comments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.Project", b =>
                {
                    b.HasOne("ProjectManagerWebAPI.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("ProjectManagerWebAPI.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId");

                    b.Navigation("Owner");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.ProjectManagerHistory", b =>
                {
                    b.HasOne("ProjectManagerWebAPI.Models.Project", "Project")
                        .WithMany("ManagerHistory")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.ProjectMember", b =>
                {
                    b.HasOne("ProjectManagerWebAPI.Models.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagerWebAPI.Models.User", "User")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.ProjectOwnerHistory", b =>
                {
                    b.HasOne("ProjectManagerWebAPI.Models.Project", "Project")
                        .WithMany("OwnerHistory")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.ProjectStatusHistory", b =>
                {
                    b.HasOne("ProjectManagerWebAPI.Models.Project", "Project")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.ProjectTask", b =>
                {
                    b.HasOne("ProjectManagerWebAPI.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.UserSetor", b =>
                {
                    b.HasOne("ProjectManagerWebAPI.Models.Setor", "Setor")
                        .WithMany("UserSetores")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagerWebAPI.Models.User", "User")
                        .WithMany("UserSetores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.Project", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ManagerHistory");

                    b.Navigation("OwnerHistory");

                    b.Navigation("ProjectMembers");

                    b.Navigation("StatusHistory");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.Setor", b =>
                {
                    b.Navigation("UserSetores");
                });

            modelBuilder.Entity("ProjectManagerWebAPI.Models.User", b =>
                {
                    b.Navigation("ProjectMembers");

                    b.Navigation("UserSetores");
                });
#pragma warning restore 612, 618
        }
    }
}
